version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      LOGGING_LEVEL_ROOT: DEBUG

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zeebe:
    image: camunda/zeebe:8.5.0
    environment:
      ZEEBE_LOG_LEVEL: debug
    ports:
      - "26500:26500"

  operate:
    image: camunda/operate:8.5.0
    ports:
      - "8081:8080"
    environment:
      CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS: zeebe:26500
      CAMUNDA_OPERATE_ELASTICSEARCHURL: http://elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"

  kafka-connector-runtime:
    image: camunda/connectors-bundle:8.5.0
    depends_on:
      - zeebe
      - kafka
    environment:
      ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS: zeebe:26500
      ZEEBE_CLIENT_SECURITY_PLAINTEXT: "true"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

