#zeebe.client.cloud.clusterId=YOUR_CLUSTER_ID
#zeebe.client.cloud.clientId=YOUR_CLIENT_ID
#zeebe.client.cloud.clientSecret=YOUR_CLIENT_SECRET

kafka:
  topic: camunda-kafka-topic
  groupId: groupId

zeebe.client.broker.gatewayAddress: 127.0.0.1:26500
zeebe.client.security.plaintext: true
spring.main.allow-bean-definition-overriding: true

spring.kafka.bootstrap-servers: localhost:9092
#spring.kafka.consumer.auto-offset-reset: earliest

