apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zeebe-gateway
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  tls:
  - hosts:
    - grpc.localhost:9993
    secretName: "mycert"
  rules:
  - host: grpc.localhost:9993
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: camunda-platform-zeebe-gateway
            port:
              number: 26500